
package server.fileServer.ws.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileServerClassWSService", targetNamespace = "http://ws.fileServer.server/", wsdlLocation = "http://localhost:8000/FileServer?wsdl")
public class FileServerClassWSService
    extends Service
{

    private final static URL FILESERVERCLASSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESERVERCLASSWSSERVICE_EXCEPTION;
    private final static QName FILESERVERCLASSWSSERVICE_QNAME = new QName("http://ws.fileServer.server/", "FileServerClassWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/FileServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESERVERCLASSWSSERVICE_WSDL_LOCATION = url;
        FILESERVERCLASSWSSERVICE_EXCEPTION = e;
    }

    public FileServerClassWSService() {
        super(__getWsdlLocation(), FILESERVERCLASSWSSERVICE_QNAME);
    }

    public FileServerClassWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESERVERCLASSWSSERVICE_QNAME, features);
    }

    public FileServerClassWSService(URL wsdlLocation) {
        super(wsdlLocation, FILESERVERCLASSWSSERVICE_QNAME);
    }

    public FileServerClassWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESERVERCLASSWSSERVICE_QNAME, features);
    }

    public FileServerClassWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileServerClassWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileServerClassWS
     */
    @WebEndpoint(name = "FileServerClassWSPort")
    public FileServerClassWS getFileServerClassWSPort() {
        return super.getPort(new QName("http://ws.fileServer.server/", "FileServerClassWSPort"), FileServerClassWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileServerClassWS
     */
    @WebEndpoint(name = "FileServerClassWSPort")
    public FileServerClassWS getFileServerClassWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.fileServer.server/", "FileServerClassWSPort"), FileServerClassWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESERVERCLASSWSSERVICE_EXCEPTION!= null) {
            throw FILESERVERCLASSWSSERVICE_EXCEPTION;
        }
        return FILESERVERCLASSWSSERVICE_WSDL_LOCATION;
    }

}
