
package server.fileServer.ws.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileServerClassWS", targetNamespace = "http://ws.fileServer.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileServerClassWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns server.fileServer.ws.services.FileInfo
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileInfo", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetFileInfo")
    @ResponseWrapper(localName = "getFileInfoResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetFileInfoResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/getFileInfoRequest", output = "http://ws.fileServer.server/FileServerClassWS/getFileInfoResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://ws.fileServer.server/FileServerClassWS/getFileInfo/Fault/InfoNotFoundException")
    })
    public FileInfo getFileInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeFile", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.RemoveFile")
    @ResponseWrapper(localName = "removeFileResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.RemoveFileResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/removeFileRequest", output = "http://ws.fileServer.server/FileServerClassWS/removeFileResponse")
    public boolean removeFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveFile", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.ReceiveFile")
    @ResponseWrapper(localName = "receiveFileResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.ReceiveFileResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/receiveFileRequest", output = "http://ws.fileServer.server/FileServerClassWS/receiveFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://ws.fileServer.server/FileServerClassWS/receiveFile/Fault/IOException")
    })
    public boolean receiveFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeDir", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.MakeDir")
    @ResponseWrapper(localName = "makeDirResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.MakeDirResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/makeDirRequest", output = "http://ws.fileServer.server/FileServerClassWS/makeDirResponse")
    public boolean makeDir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendFile", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.SendFile")
    @ResponseWrapper(localName = "sendFileResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.SendFileResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/sendFileRequest", output = "http://ws.fileServer.server/FileServerClassWS/sendFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://ws.fileServer.server/FileServerClassWS/sendFile/Fault/IOException")
    })
    public boolean sendFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetNameResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/getNameRequest", output = "http://ws.fileServer.server/FileServerClassWS/getNameResponse")
    public String getName();

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFile", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetFile")
    @ResponseWrapper(localName = "getFileResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetFileResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/getFileRequest", output = "http://ws.fileServer.server/FileServerClassWS/getFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://ws.fileServer.server/FileServerClassWS/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHost", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetHost")
    @ResponseWrapper(localName = "getHostResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.GetHostResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/getHostRequest", output = "http://ws.fileServer.server/FileServerClassWS/getHostResponse")
    public String getHost();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dir", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.Dir")
    @ResponseWrapper(localName = "dirResponse", targetNamespace = "http://ws.fileServer.server/", className = "server.fileServer.ws.services.DirResponse")
    @Action(input = "http://ws.fileServer.server/FileServerClassWS/dirRequest", output = "http://ws.fileServer.server/FileServerClassWS/dirResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://ws.fileServer.server/FileServerClassWS/dir/Fault/InfoNotFoundException")
    })
    public List<String> dir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InfoNotFoundException_Exception
    ;

}
