
package server.contactServer.ws.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactServerClassWSService", targetNamespace = "http://ws.contactServer.server/", wsdlLocation = "http://10.22.135.224/contactServer?wsdl")
public class ContactServerClassWSService
    extends Service
{

    private final static URL CONTACTSERVERCLASSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACTSERVERCLASSWSSERVICE_EXCEPTION;
    private final static QName CONTACTSERVERCLASSWSSERVICE_QNAME = new QName("http://ws.contactServer.server/", "ContactServerClassWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.22.135.224/contactServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTSERVERCLASSWSSERVICE_WSDL_LOCATION = url;
        CONTACTSERVERCLASSWSSERVICE_EXCEPTION = e;
    }

    public ContactServerClassWSService() {
        super(__getWsdlLocation(), CONTACTSERVERCLASSWSSERVICE_QNAME);
    }

    public ContactServerClassWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTSERVERCLASSWSSERVICE_QNAME, features);
    }

    public ContactServerClassWSService(URL wsdlLocation) {
        super(wsdlLocation, CONTACTSERVERCLASSWSSERVICE_QNAME);
    }

    public ContactServerClassWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTSERVERCLASSWSSERVICE_QNAME, features);
    }

    public ContactServerClassWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactServerClassWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactServerClassWS
     */
    @WebEndpoint(name = "ContactServerClassWSPort")
    public ContactServerClassWS getContactServerClassWSPort() {
        return super.getPort(new QName("http://ws.contactServer.server/", "ContactServerClassWSPort"), ContactServerClassWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactServerClassWS
     */
    @WebEndpoint(name = "ContactServerClassWSPort")
    public ContactServerClassWS getContactServerClassWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.contactServer.server/", "ContactServerClassWSPort"), ContactServerClassWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTSERVERCLASSWSSERVICE_EXCEPTION!= null) {
            throw CONTACTSERVERCLASSWSSERVICE_EXCEPTION;
        }
        return CONTACTSERVERCLASSWSSERVICE_WSDL_LOCATION;
    }

}
